overrides:
  '@babel/core@<=7.29.0': '>=7.29.6'
  brace-expansion@<1.1.13: '>=1.1.13'
  brace-expansion@<1.1.16: '>=1.1.16'
  brace-expansion@<1.1.17: '>=1.1.17'
  js-yaml@<3.15.0: '>=3.15.0'
  js-yaml@>=3.0.0 <3.15.0: '>=3.15.0'
  picomatch@<2.3.2: '>=2.3.2'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  postcss@<8.5.10: '>=8.5.10'
  postcss@<=8.5.11: '>=8.5.12'
  postcss@<=8.5.17: '>=8.5.18'
  shell-quote@<=1.8.4: '>=1.9.0'
  shell-quote@>=1.1.0 <=1.8.3: '>=1.8.4'
  ws@>=7.0.0 <7.5.11: '>=7.5.11'
  yaml@>=2.0.0 <2.8.3: '>=2.8.3'
